name: Build and Push Spark 3.4 Image

on:
  workflow_dispatch:

jobs:
  build_and_push_spark_image:
    name: Build spark base image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build, tag, and push image to Docker Hub
      uses: docker/build-push-action@v5
      env:
        REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        REPOSITORY: spark
        IMAGE_TAG: v3.4.2-hadoop3
      run: |
        cd $IMAGE_PATH
        ./bin/docker-image-tool.sh -r $REGISTRY -t $IMAGE_TAG -p ./kubernetes/dockerfiles/spark/bindings/python/Dockerfile -X build
        
env:
  IMAGE_PATH : "spark-3.4.2-bin-hadoop3"