name: Build and Push Spark Image

on:
  workflow_dispatch:

jobs:
  build_and_push_spark_image:
    name: Build spark base image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    - name: Build, tag, and push image to Docker Hub
      env:
        REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        REPOSITORY: spark
        IMAGE_TAG: v3.2.3-hadoop3
      run: |
        cd $IMAGE_PATH
        ./bin/docker-image-tool.sh -r $REPOSITORY -t $IMAGE_TAG build
        ./bin/docker-image-tool.sh -r $REPOSITORY -t $IMAGE_TAG push
        
env:
  IMAGE_PATH : "spark-3.2.3-bin-hadoop3.2"