name: Build and Push Spark Image

on:
  workflow_dispatch:

jobs:
  build_and_push_spark_image:
    name: Build spark base image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build, tag, and push image to Docker Hub
      env:
        REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        REPOSITORY: spark-py
        IMAGE_TAG: v3.3.2-hadoop3
      run: |
        cd $IMAGE_PATH
        ./bin/docker-image-tool.sh -r $REGISTRY -t $IMAGE_TAG -p ./kubernetes/dockerfiles/spark/bindings/python/Dockerfile build
        ./bin/docker-image-tool.sh -r $REGISTRY -t $IMAGE_TAG push
        
env:
  IMAGE_PATH : "spark-3.3.2-bin-hadoop3"